# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7k325tffg900-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/LabVIEW_to_VHDL_projects/Ethernet_2/Ethernet_2.cache/wt [current_project]
set_property parent.project_path E:/LabVIEW_to_VHDL_projects/Ethernet_2/Ethernet_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet E:/LabVIEW_to_VHDL_projects/Ethernet_2/Ethernet_2.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files E:/LabVIEW_to_VHDL_projects/Ethernet_2/Ethernet_2.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_vhdl -library xil_defaultlib {
  E:/LabVIEW_to_VHDL_projects/Ethernet_2/Ethernet_2.srcs/sources_1/new/udp_rx.vhd
  E:/LabVIEW_to_VHDL_projects/Ethernet_2/Ethernet_2.srcs/sources_1/new/udp_tx.vhd
  E:/LabVIEW_to_VHDL_projects/Ethernet_2/Ethernet_2.srcs/sources_1/new/udp_echo_top.vhd
}
read_xdc E:/LabVIEW_to_VHDL_projects/Ethernet_2/Ethernet_2.srcs/constrs_1/new/AX7325_eth.xdc
set_property used_in_implementation false [get_files E:/LabVIEW_to_VHDL_projects/Ethernet_2/Ethernet_2.srcs/constrs_1/new/AX7325_eth.xdc]

catch { write_hwdef -file udp_echo_top.hwdef }
synth_design -top udp_echo_top -part xc7k325tffg900-2
write_checkpoint -noxdef udp_echo_top.dcp
catch { report_utilization -file udp_echo_top_utilization_synth.rpt -pb udp_echo_top_utilization_synth.pb }
