# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/LabVIEW_to_VHDL_projects/UART_LV_to_VHDL/UART_LV_to_VHDL.srcs/sources_1/ip/fifo_async_8x1024/fifo_async_8x1024.xci
# IP: The module: 'fifo_async_8x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/LabVIEW_to_VHDL_projects/UART_LV_to_VHDL/UART_LV_to_VHDL.srcs/sources_1/ip/fifo_async_8x1024/fifo_async_8x1024/fifo_async_8x1024_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async_8x1024'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/LabVIEW_to_VHDL_projects/UART_LV_to_VHDL/UART_LV_to_VHDL.srcs/sources_1/ip/fifo_async_8x1024/fifo_async_8x1024/fifo_async_8x1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async_8x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/LabVIEW_to_VHDL_projects/UART_LV_to_VHDL/UART_LV_to_VHDL.srcs/sources_1/ip/fifo_async_8x1024/fifo_async_8x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async_8x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/LabVIEW_to_VHDL_projects/UART_LV_to_VHDL/UART_LV_to_VHDL.srcs/sources_1/ip/fifo_async_8x1024/fifo_async_8x1024.xci
# IP: The module: 'fifo_async_8x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/LabVIEW_to_VHDL_projects/UART_LV_to_VHDL/UART_LV_to_VHDL.srcs/sources_1/ip/fifo_async_8x1024/fifo_async_8x1024/fifo_async_8x1024_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async_8x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/LabVIEW_to_VHDL_projects/UART_LV_to_VHDL/UART_LV_to_VHDL.srcs/sources_1/ip/fifo_async_8x1024/fifo_async_8x1024/fifo_async_8x1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async_8x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/LabVIEW_to_VHDL_projects/UART_LV_to_VHDL/UART_LV_to_VHDL.srcs/sources_1/ip/fifo_async_8x1024/fifo_async_8x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async_8x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
